Import the relevant libraries

In [1]:
import numpy as np

Declaring scalars, vectors, and matrices

Scalars

In [2]:
s = 5

In [3]:
s

5

Vectors

In [4]:
v = np.array([5, -2,4])

In [5]:
v

array([ 5, -2,  4])

Matrices

In [6]:
m = np.array([[5, 12, 6], [-3, 0, 14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

Data Types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array(5)
s_array

array(5)

In [12]:
type(s_array)

numpy.ndarray

Data Shapes

In [13]:
m.shape

(2, 3)

In [14]:
v.shape

(3,)

In [15]:
# s.shape # AttributeError: 'int' object has no attribute 'shape'
s_array.shape

()

Create a column vector

In [16]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [17]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])