In [2]:
import numpy as np

Transpose is to swap a matrix columns to rows and viceversa. (3x2) => (2x3)

In [3]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [8]:
# Transposing Scalars
s = np.array([5])
s.T

array([5])

In [9]:
# Transposing Vectors
x = np.array([1,2,3])
x

array([1, 2, 3])

In [10]:
x.T

array([1, 2, 3])

In [11]:
x.shape

(3,)

In [12]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [13]:
x_reshaped.T

array([[1],
       [2],
       [3]])