In [1]:
import numpy as np

In [2]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [4]:
np.dot(x,y)

np.int64(-66)

In [5]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [6]:
np.dot(u,v)

np.int64(18)

In [7]:
# Scalar * Scalar
np.dot(5,6)

np.int64(30)

In [8]:
np.dot(10,-2)

np.int64(-20)

In [9]:
#Scalar * Vector
x

array([ 2,  8, -4])

In [10]:
5*x

array([ 10,  40, -20])

In [11]:
# Scalar * Matrix
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [13]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

In [14]:
# Matrix * Matrix
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [15]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])